=== labs-comp4711/timetable-lab/data/schedule.dtd
<!ELEMENT schedule (timeslots, days, courses)>

		<!--Timeslots facet definitions-->
		<!ELEMENT timeslots (slots*)>
		<!ELEMENT slots (timeEntry*)>
			<!ATTLIST slots
				start (0830|0930|1030|1130|1230|1330|1430|1530) #REQUIRED
				>
		<!ELEMENT timeEntry (bookingroom, day, course, instructor, type)>

		<!--Courses facet definition-->
		<!ELEMENT courses (course*)>
		<!ELEMENT course (courseEntry*)>
			<!ATTLIST course
				code (BLAW3600|COMP4560|COMP4711|COMP4735|COMP4981|COMP4985) #REQUIRED
				>
		<!ELEMENT courseEntry (day, time, bookingroom, instructor, type)>

		<!--Days facet definition-->
		<!ELEMENT days (day*)>
		<!ELEMENT day (dayEntry*)>
		<!ATTLIST day
				name (Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday) #REQUIRED
				>
		<!ELEMENT dayEntry (bookingroom, time, course, instructor, type)>


		<!ELEMENT bookingroom (#PCDATA)>
		<!ELEMENT instructor (#PCDATA)>
		<!ELEMENT type (#PCDATA)>
		<!ELEMENT time (#PCDATA)>
			<!ATTLIST time
				start (0830|0930|1030|1130|1230|1330|1430|1530) #REQUIRED
				>

=== labs-comp4711/timetable-lab/data/timetable.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE schedule SYSTEM "schedule.dtd">
<schedule>

    <timeslots>
        <slots start="0830">
            <timeEntry>
                <bookingroom>SW5-1840</bookingroom>
                <day name="Friday"></day>
                <course code="BLAW3600"></course>
                <instructor>Catherine Ryan</instructor>
                <type>Lecture</type>
            </timeEntry>
        </slots>
        <slots start="0930">
            <timeEntry>
                <bookingroom>SE12-323</bookingroom>
                <day name="Monday"></day>
                <course code="COMP4985"></course>
                <instructor>Aman Abdulla</instructor>
                <type>Lab</type>
            </timeEntry>
            <timeEntry>
                <bookingroom>SE12-323</bookingroom>
                <day name="Tuesday"></day>
                <course code="COMP4981"></course>
                <instructor>Aman Abdulla</instructor>
                <type>Lab</type>
            </timeEntry>
            <timeEntry>
                <bookingroom>SE12-323</bookingroom>
                <day name="Wednesday"></day>
                <course code="COMP4985"></course>
                <instructor>Aman Abdulla</instructor>
                <type>Lecture</type>
            </timeEntry>
            <timeEntry>
                <bookingroom>SE12-323</bookingroom>
                <day name="Thursday"></day>
                <course code="COMP4981"></course>
                <instructor>Aman Abdulla</instructor>
                <type>Lecture</type>
            </timeEntry>
        </slots>
        <slots start="1130">
            <timeEntry>
                <bookingroom>SW1-1205</bookingroom>
                <day name="Monday"></day>
                <course code="COMP4735"></course>
                <instructor>Mirela Gutica</instructor>
                <type>Lecture</type>
            </timeEntry>
            <timeEntry>
                <bookingroom>SW5-1850</bookingroom>
                <day name="Tuesday"></day>
                <course code="COMP4560"></course>
                <instructor>Brenda Fine</instructor>
                <type>Lecture</type>
            </timeEntry>
            <timeEntry>
                <bookingroom>SE12-323</bookingroom>
                <day name="Wednesday"></day>
                <course code="COMP4985"></course>
                <instructor>Aman Abdulla</instructor>
                <type>Lecture</type>
            </timeEntry>
            <timeEntry>
                <bookingroom>SW3-1710</bookingroom>
                <day name="Thursday"></day>
                <course code="COMP4735"></course>
                <instructor>Mirela Gutica</instructor>
                <type>Lecture</type>
            </timeEntry>
        </slots>
        <slots start="1230">
            <timeEntry>
                <bookingroom>SW9-127</bookingroom>
                <day name="Monday"></day>
                <course code="BLAW3600"></course>
                <instructor>Catherine Ryan</instructor>
                <type>Lab</type>
            </timeEntry>
            <timeEntry>
                <bookingroom>SE12-323</bookingroom>
                <day name="Wednesday"></day>
                <course code="COMP4981"></course>
                <instructor>Aman Abdulla</instructor>
                <type>Lecture</type>
            </timeEntry>
            <timeEntry>
                <bookingroom>SW3-1750</bookingroom>
                <day name="Thursday"></day>
                <course code="COMP4560"></course>
                <instructor>Brenda Fine</instructor>
                <type>Lecture</type>
            </timeEntry>
        </slots>
        <slots start="1330">
            <timeEntry>
                <bookingroom>SW1-1205</bookingroom>
                <day name="Wednesday"></day>
                <course code="COMP4735"></course>
                <instructor>Mirela Gutica</instructor>
                <type>Lecture</type>
            </timeEntry>
        </slots>
        <slots start="1430">
            <timeEntry>
                <bookingroom>SW5-1840</bookingroom>
                <day name="Tuesday"></day>
                <course code="COMP4711"></course>
                <instructor>James Parry</instructor>
                <type>Lecture</type>
            </timeEntry>
        </slots>
        <slots start="1530">
            <timeEntry>
                <bookingroom>SE12-320</bookingroom>
                <day name="Monday"></day>
                <course code="COMP4560"></course>
                <instructor>Brenda Fine</instructor>
                <type>Lab</type>
            </timeEntry>
            <timeEntry>
                <bookingroom>SE12-321</bookingroom>
                <day name="Tuesday"></day>
                <course code="COMP4711"></course>
                <instructor>James Parry</instructor>
                <type>Lab</type>
            </timeEntry>
            <timeEntry>
                <bookingroom>SE12-322</bookingroom>
                <day name="Thursday"></day>
                <course code="COMP4735"></course>
                <instructor>Mathew Linder</instructor>
                <type>Lab</type>
            </timeEntry>
        </slots>
    </timeslots>

    <!-- Thomas please complete facet for days -->
    <!-- example -->
    <days>
        <day name="Monday">
            <dayEntry>
                <bookingroom>SE12-323</bookingroom>
                <time start="0930"></time>
                <course code="COMP4985"></course>
                <instructor>Aman Abdulla</instructor>
                <type>Lab</type>
            </dayEntry>
            <dayEntry>
                <bookingroom>SW1-1205</bookingroom>
                <time start="1130"></time>
                <course code="COMP4735"></course>
                <instructor>Mirela Gutica</instructor>
                <type>Lecture</type>
            </dayEntry>
            <dayEntry>
                <bookingroom>SW9-127</bookingroom>
                <time start="1230"></time>
                <course code="BLAW3600"></course>
                <instructor>Catherine Ryan</instructor>
                <type>Lab</type>
            </dayEntry>
            <dayEntry>
                <bookingroom>SE12-320</bookingroom>
                <time start="1530"></time>
                <course code="COMP4560"></course>
                <instructor>Brenda Fine</instructor>
                <type>Lab</type>
            </dayEntry>           
        </day>
        <day name="Tuesday">
            <dayEntry>
                <bookingroom>SE12-323</bookingroom>
                <time start="0930"></time>
                <course code="COMP4981"></course>
                <instructor>Aman Abdulla</instructor>
                <type>Lab</type>
            </dayEntry>
            <dayEntry>
                <bookingroom>SW5-1850</bookingroom>
                <time start="1130"></time>
                <course code="COMP4560"></course>
                <instructor>Brenda Fine</instructor>
                <type>Lecture</type>
            </dayEntry>
            <dayEntry>
                <bookingroom>SW5-1840</bookingroom>
                <time start="1430"></time>
                <course code="COMP4711"></course>
                <instructor>James Perry</instructor>
                <type>Lecture</type>
            </dayEntry>
             <dayEntry>
                <bookingroom>SE12-321</bookingroom>
                <time start="1530"></time>
                <course code="COMP4711"></course>
                <instructor>James Perry</instructor>
                <type>Lab</type>
            </dayEntry>
        </day>
        <day name="Wednesday">
            <dayEntry>
                <bookingroom>SE12-323</bookingroom>
                <time start="0930"></time>
                <course code="COMP4985"></course>
                <instructor>Aman Abdulla</instructor>
                <type>Lecture</type>
            </dayEntry>
            <dayEntry>
                <bookingroom>SE12-323</bookingroom>
                <time start="1130"></time>
                <course code="COMP4985"></course>
                <instructor>Aman Abdulla</instructor>
                <type>Lecture</type>
            </dayEntry>
            <dayEntry>
                <bookingroom>SE12-323</bookingroom>
                <time start="1230"></time>
                <course code="COMP4981"></course>
                <instructor>Aman Abdulla</instructor>
                <type>Lecture</type>
            </dayEntry>
             <dayEntry>
                <bookingroom>SW1-1205</bookingroom>
                <time start="1330"></time>
                <course code="COMP4735"></course>
                <instructor>Mirela Gutica</instructor>
                <type>Lecture</type>
            </dayEntry>                         
        </day>
        <day name="Thursday">
            <dayEntry>
                <bookingroom>SE12-323</bookingroom>
                <time start="0930"></time>
                <course code="COMP4981"></course>
                <instructor>Aman Abdulla</instructor>
                <type>Lecture</type>
            </dayEntry>
            <dayEntry>
                <bookingroom>SW3-1710</bookingroom>
                <time start="1130"></time>
                <course code="COMP4735"></course>
                <instructor>Mirela Gutica</instructor>
                <type>Lecture</type>
            </dayEntry>
             <dayEntry>
                <bookingroom>SE12-322</bookingroom>
                <time start="1530"></time>
                <course code="COMP4735"></course>
                <instructor>Mathew Linder</instructor>
                <type>Lab</type>
            </dayEntry>                         
        </day>
        <day name="Friday">
            <dayEntry>
                <bookingroom>SW5-1840</bookingroom>
                <time start="0830"></time>
